// <auto-generated />
namespace SchoolCMS.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class PageChange1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PageChange1));
        
        string IMigrationMetadata.Id
        {
            get { return "201504271805261_PageChange1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
