// <auto-generated />
namespace SchoolCMS.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class News1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(News1));
        
        string IMigrationMetadata.Id
        {
            get { return "201504281318419_News1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
