// <auto-generated />
namespace SchoolCMS.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class MenuButtonPage : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MenuButtonPage));
        
        string IMigrationMetadata.Id
        {
            get { return "201504240752431_MenuButtonPage"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
