// <auto-generated />
namespace SchoolCMS.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class cmsSettings : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(cmsSettings));
        
        string IMigrationMetadata.Id
        {
            get { return "201504300757154_cmsSettings"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
