// <auto-generated />
namespace SchoolCMS.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class menubuttonchange2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(menubuttonchange2));
        
        string IMigrationMetadata.Id
        {
            get { return "201504231722137_menubuttonchange2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
